### ISSUE TITLE
Images on IFComp (especially /results) could be optimized re: caching

### ISSUE THREAD

**Issue by furkle** [iftechfoundation/ifcomp#101]
There appears to be no `Cache-Control` directive in responses sent from ifcomp.org. While most requests (e.g. all of mine on the most recent stable Chrome build) likely have `Cache-Control: no-cache` on them, resulting (despite the what the name seems to suggest) in both memory and file caching if the resource has not been updated, there is still a requirement for revalidation of the resources. Given that these images are almost 100% likely to be invariant across the life of the comp, and would probably be recreated with a unique filename even if they were changed, we could save both server time and bandwidth by adding a `Cache-Control: max-age: ${oneYearInSeconds}` directive to image responses.

**Comment by dfabulich** [comment]
I poked around in the code; this isn't easy to do. All content in the `root/static` directory is being served by `Catalyst::Plugin::Static::Simple`, configured in `lib/IFComp.pm`. It's possible to set an `expires` header on all static files, but `Static::Simple` offers no way to configure cache headers on just the cover-art images.

Fixing this would presumably require ripping out `Static::Simple` and replacing it with another library with more configuration options. (Even just Apache `htaccess` files would be a big improvement.)

**Comment by furkle** [comment]
Thanks Dan, I hadn't actually looked at the implementation. I should also note that I should've said in the first place to use `Cache-Control: public, max-age: 31536000, immutable` rather than just `max-age`.

**Comment by jmacdotorg** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Have images send better cache headers](https://trello.com/c/rlGKcEPY/30-have-images-send-better-cache-headers)

**Comment by furkle** [comment]
In case it's unintentional, I can't see any of the content at that link, as it's a private board.

**Comment by jmacdotorg** [comment]
My bad... I didn't realize that my Trello organization would spam all these tickets, ooops

**Comment by jmacdotorg** [comment]
I'm addressing this by letting Apache butt in and handle all content in /static/images (per the suggestion at https://metacpan.org/pod/Catalyst::Plugin::Static::Simple#USING-WITH-APACHE). It merges in the suggested header while doing so.

This is on staging now, and am awaiting comment from the rest of the tech team.

**Comment by jmacdotorg** [comment]
For the record, this is the proposed Apache config:

```
    <Location /static/images/>
        SetHandler default-handler
    </Location>

    <Location /static/images/covers/>
        Header merge Cache-Control "public, max-age=31556000, immutable"
    </Location>
```

**Comment by furkle** [comment]
it looks great, one slight typo: one year is actually `31536000`; yours is two thousand seconds longer than the general max value. generally that should be taken by every browser and server as equivalent, i believe, so it's not anything more than just a typo.

**Comment by jmacdotorg** [comment]
This is live in production now.
