### ISSUE TITLE
Cosmetic issue: file name is highlighted vs. browser button on uploading

### ISSUE THREAD

**Issue by andrewschultz** [iftechfoundation/ifcomp#102]
On Firefox:

* go to update an entry
* click on "No File Selected" (if there is a file name, click that)
* note that the dotted box surrounds the "browse" button and the file name/"No File Selected"

However, if you tab back and forth, only the Browse button is highlighted, and the file name can't be highlighted again.

This is a minor stylistic thing, and fixing this means you can't click the file name to re-upload the file, that's not worth it. But if there's a one line fix, great!

**Comment by jmacdotorg** [comment]
Thanks for noticing, but I'm closing this coz I'm pretty sure this is a browser-based issue. The form element you describe here is a standard HTML file-upload field. If a browser can get it into a weird but non-disastrous state, which sounds like the case here, then I don't think this is worth our worry.
