### ISSUE TITLE
extra carriage return in IE

### ISSUE THREAD

**Issue by andrewschultz** [iftechfoundation/ifcomp#108]
http://dev.ifcomp.org/about/guidelines

has a carriage return before the third entry on IE. I can't test in other browsers at the moment, but I will later.

**Comment by jmacdotorg** [comment]
I'm not sure what you mean by "the third entry". Could you attach a screenshot, please?

**Comment by erkyrath** [comment]
The line

    <li></p><a href="http://www.amazon.com/IF-Theory-Reader-Adventure-beyond-ebook/dp/B00JHCSU0Y">An e-book in Kindle format</a>, from Amazon</p></li>

has mismatched opening <p> tag, was that the problem?

(Yay browsers with built-in HTML checking)

**Comment by jmacdotorg** [comment]
@andrewschultz, does Zarf's comment address the location of the problem you found?
