### ISSUE TITLE
twitter handle edge cases

### ISSUE THREAD

**Issue by andrewschultz** [iftechfoundation/ifcomp#109]
If someone wants to be "clever" and, say, give the handle ifcomp (or something profane, even if it's really theirs) should we let them on the form, or will the organizer be able to sort that out?

More happily, it's good that the site allows people to input the handle with or without the at-sign. Should we mention this e.g. "Twitter handle (no @ necessary)" or is it not worth the bother?

(Note I've also noticed some other cases that aren't cool, like putting "admin" or "twitter" in the user name. These aren't allowed by Twitter, but is it ifcomp's responsibility or wish to flag them?)

**Comment by jmacdotorg** [comment]
I'm filing this as a policy issue, if anything, not a tech one.
