### ISSUE TITLE
twitter handle obvious error rejects

### ISSUE THREAD

**Issue by andrewschultz** [iftechfoundation/ifcomp#111]
While the user should be able to figure why a twitter handle is wrong, it would be nice to give a bit more information:

* the text length is more than 15 characters
* the @ needs to be at the start
* there are illegal characters in the twitter handle
* the user entered the URL to their twitter handle

Failing that, we could give the user a link if it's not clear why it's wrong.

(Note a workaround would be to limit the twitter input field to 16 letters)

**Comment by jmacdotorg** [comment]
This is really just add-on thoughts for addressing #111, so I'll turn it into a comment there.
