### ISSUE TITLE
What sort of URLs are (un)acceptable?

### ISSUE THREAD

**Issue by andrewschultz** [iftechfoundation/ifcomp#112]
If we go to our profile page, we can allow a cgi, or a tinyurl, or something like that. Do we want to protect against this? How much link vetting do we want to do?

**Comment by jmacdotorg** [comment]
I would be concerned here only if a malicious entrant could execute a JavaScript-based injection attack through these fields. E.G. submitting a URL value of "</a><script>alert("Evil Script here, mu hu ha ha ha")</script><a href="#">"

This could stand some testing, for all the publicly displayed author-definable fields. I'll do that and report back.

Anything else I should be on he lookout for?

**Comment by jmacdotorg** [comment]
No further response, so closing this as answered.
