### ISSUE TITLE
Can we warn an author if their ZIP file has 2 binary inform files?

### ISSUE THREAD

**Issue by andrewschultz** [iftechfoundation/ifcomp#125]
[2games.zip](https://github.com/iftechfoundation/ifcomp/files/1203050/2games.zip)

I attached a zip file with 2 simple zblorbs. It seems like the game picks the one created latest, which is probably what the author wants. But just in case, can we run a check to warn the author if they have more than one z5/z8/zblorb/glx/gblorb file in their ZIP?

**Comment by jmacdotorg** [comment]
This is a completely unexpected situation, and which file is chosen as the story file probably falls into the realm of "undefined behavior".

I'm not sure how much into the business of policing .zip content I want to get, as we can imagine other kinds of bizarrely shaped uploads besides this one.

If the author wants to upload something weird, on their head be it. I think I'm in favor of continuing to keep the current behavior as it is, allowing authors to preview their games' online behavior and then either adjusting their upload or contacting the organizers with questions.

Other thoughts?

**Comment by jmacdotorg** [comment]
Closing this as answered. ("No.")
