### ISSUE TITLE
Can IFComp.org allow the author to delete transcripts?

### ISSUE THREAD

**Issue by andrewschultz** [iftechfoundation/ifcomp#128]
This would be useful to keep things organized. I'm aware feature requests right now have a low chance of being fulfilled, but in case there's an easy way to do this, here it is.

**Comment by jmacdotorg** [comment]
Gonna answer this with "Yes, in fact it should allow transcripts to be downloaded as files *and* deleted." This goes hand-in-hand with the fact that transcripts should be stored as files to begin with an not as database rows. So, will wrap this into that future enhancement.
