### ISSUE TITLE
Feature request: can authors label transcripts?

### ISSUE THREAD

**Issue by andrewschultz** [iftechfoundation/ifcomp#129]
This is probably more ambitious than #128, but it would be handy for authors to say--ok, I'm working on this transcript, and I'm not sure what to do with it, but it's an important bug to fix in my work in the future.

I'm not sure how tricky this would be, but it would be an obvious help for updates or tracking a quick post-comp release.

**Comment by jmacdotorg** [comment]
No, the correct thing to do is let authors download their transcripts as local files, and then arrange them however they like locally.
