### ISSUE TITLE
Add a "Is this unreleased work?" question to the entry form

### ISSUE THREAD

**Issue by jmacdotorg** [iftechfoundation/ifcomp#132]
Add a question to the entry form to force a little more attention onto author rule 3. An answer is required for valid form submission.

Question: some form of "Is this unreleased work?"

Answer: Radio buttons "Yes" and "No", no default response.

If "No" is selected, un-hide a hidden div warning that this game might not qualify for entry, due to conflicts with rule 3.

If "Yes" is selected, hide the div.

Submitting the form with "No" selected is OK, maybe? (Which is to say: the controller needn't pay any attention to the answer. The field is mainly there to force authors to reckon with the oft-overlooked rule 3.)

**Comment by erkyrath** [comment]
This is probably just a comment thinko, but the way you described it above, it's backwards.

**Comment by jmacdotorg** [comment]
Indeed it was. Fixed, thanks.

**Comment by jmacdotorg** [comment]
Implemented and shipped in time for 2018.
