### ISSUE TITLE
Link to parchment repository gets in the way of the prompt after continue the play after a Pause the game (mobile)

### ISSUE THREAD

**Issue by rubereaglenest** [iftechfoundation/ifcomp#148]
Hi,

Parchment is really nice for playing IF on mobile, but there's a glitch or problem with it with the template used by the ifcomp site; after passing a "Pause the game". I've tested this on Android. In any zblorb game at the ifcomp site.

After a "Pause the game" or "Press any key", the game continues, but now the link to the parchment repository labeled as "Parchment for Inform 7" is printed just on top of the prompt. It is not a game breaker bug because we can bring the virtual keyboard up hitting any place in the mobile screen, but players usually hit the place where the prompt is, so the link is activated and the navigation jump to this repository, losing all progress in the game.

That is, by default, the mobile view of Parchment do it great hiding that link, but in a somewhat manner, that css trick fails after returning from a Pause or Press any key.

Anyway, my recommendation is to avoid use any CSS template at all.  Barebones parchment works already great in mobile.

Regards.

**Comment by jmacdotorg** [comment]
Marking as major; anything that gets in the way of playing games is worth more immediate attention.

**Comment by jmacdotorg** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Address Parchment "Pause" display bug](https://trello.com/c/JcY6JKDG/15-address-parchment-pause-display-bug)

**Comment by curiousdannii** [comment]
This is likely not relevant anymore. The Parchment pages that the comp site builds won't have the link, and if someone uploads a Parchment site as produced by Inform 7 themselves, then we don't alter their code at all, so any bugs should be reported to the entry author (or to Inform 7).
