### ISSUE TITLE
Spaces collapse in uploaded Glulx games

### ISSUE THREAD

**Issue by erkyrath** [iftechfoundation/ifcomp#151]
A user uploaded a Glulx game website using Quixe 2.1.6 (the latest released version). The ifcomp web site uses a slightly newer bleeding-edge build of Quixe.

The transcript hack (`_mangle_quixe_head`) changes the "interpreter/glkote.min.js" link in play.html to refer to "/static/interpreter/quixe/lib/glkote.min.js", but it does not change "interpreter/glkote.css". This causes a version skew problem.

(Specifically, the uploaded glkote.css file is missing this line:

    white-space: pre-wrap; /* required for spaces to work right */

This line is only needed in the bleeding-edge build because Quixe used to handle spaces differently. See https://github.com/erkyrath/glkote/issues/26 if you really want the details.)

Anyhow, the fix is to change "interpreter/glkote.css" to "/static/interpreter/quixe/media/i7-glkote.css". (Note this is not the same filename on the end!)

**Comment by erkyrath** [comment]
The problem showed up with (current entry submission) https://ifcomp.org/1825/content/index.html -- type MENU to see the wrong spacing.

**Comment by jmacdotorg** [comment]
N.B. that that link only works for users with curator-level access to IFComp. (Happily, this includes me.)

**Comment by erkyrath** [comment]
Possible down side: if an author hacks around with the glkote.css file to achieve custom fonts or styles, this change will drop those customizations.

I don't know if any authors are actually doing this. If they are, we may have to get them to rearrange their files. (Moving all the customizations to a separate .css file should suffice.)

**Comment by jmacdotorg** [comment]
@erkyrath Please confirm that it looks & works as expected now? (I had to shift-reload play.html to force a fresh download of the CSS file.)

**Comment by erkyrath** [comment]
Yup, all good.
