### ISSUE TITLE
Server-side cache sometimes caches an empty string for a page

### ISSUE THREAD

**Issue by jmacdotorg** [iftechfoundation/ifcomp#160]
Sometimes, the server-side cache (provided by the Catalyst::Plugin::PageCache module) caches an empty string instead of the contents of a page. This appears to happen more commonly after a server restart. When it does happen, users will sometimes get a blank page instead the expected content, until that cache clears itself.

**Comment by jmacdotorg** [comment]
My current leaning is that we fix this by removing use of this caching module from the codebase entirely, and instead investigate the use of caching outside of the application: via a CDN service, or a locally run service like Squid.

**Comment by erkyrath** [comment]
If you set up a CDN service, remember that other IFTF programs might want to use it someday.

**Comment by jmacdotorg** [comment]
You know what, I want to re-examine some basic assumptions here.

The main reason we have server-side caching in the first place is to handle the two big annual spikes in traffic, when the entries are first opened to the public, and then when the results get posted.

I don't think we've ever done any load-testing for how well the plain old software can handle heavy loads, and certainly not since we moved the application to its own server.

So I would like to do some benchmarking, as a next step, and see if we can just remove this caching entirely.

**Comment by jmacdotorg** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Fix nasty cache bug](https://trello.com/c/eZPl26MH/19-fix-nasty-cache-bug)

**Comment by jmacdotorg** [comment]
Well this problem started biting people again on launch day 2019 (today), and obviously I didn't do any of that stuff I described above.

But I'm still doubtful that this is even necessary. I've experimentally shut this off in production (just deleting the one invocation of "PageCache" from lib/IFComp.pm). If things seems to work OK I'll just remove it from the codebase.

**Comment by jmacdotorg** [comment]
Further realization: we changed the ballot to randomize by default this year, and this is fundamentally incompatible with the cache anyway. 🤦‍♂

**Comment by curiousdannii** [comment]
The randomised ballot could be done fairly easily client side - send all the games alphabetically and randomise in JS. A random seed could be stored in localStorage to allow for persistent personal random orders. Or with cookies to let you have the same order across browsers if you're logged in.

**Comment by mjmusante** [comment]
My argument against using local cache is then the random seed is per-browser rather than per-judge
