### ISSUE TITLE
2017 comp entry page gives security risk in Firefox 69.0.1/Chrome

### ISSUE THREAD

**Issue by andrewschultz** [iftechfoundation/ifcomp#196]
I found this link while googling some other stuff ("site:ifcomp.org github")

I don't know if you want to fix the issue on the page, or if you want to use robots.txt to block older entries, and I doubt it's major, but I turned it up.

**Comment by erkyrath** [comment]
Does it say what the security risk is?

**Comment by jmacdotorg** [comment]
I can't reproduce this on the current version (Mac) of either browser, so I'm closing it.
