### ISSUE TITLE
Let authors identify their entries' platforms

### ISSUE THREAD

**Issue by jmacdotorg** [iftechfoundation/ifcomp#201]
**Deadline: July 1, 2020**

At present, the software determines the platform of each entry (e.g. Z-code, Web-based, Windows executable, et cetera) by examining the names and relative path locations of its constituent files.

This seemed clever in 2014, and a lot of smart people contributed clever code to the cause, but it invariably gets some entries wrong -- probably a few more every year, as we have more entries with more variety. And this always causes headaches for both organizers and authors.

We should let authors name each entry's platform in the entry form, and store it in the database like any other field.

This work involves:

* Adding a field to entry objects to store the platform.
* Adding a field to the author-visible entry form for specifying the platform
    * The field should be limited vocabulary (i.e. a dropdown menu) whose possible values match the platforms that the software already knows about.
    * This field should be near the top of the form, at or near the level of the game's title.
    * It will not be required for intents (where the only required field remains title), but encouraged.
* Changing the entry-object code so that instead of doing all the lazy-load calculation it currently does to determine the platform, it simply checks this value. (All that old logic can be simply discarded.)

**Comment by jmacdotorg** [comment]
I would also note that, increasingly, entries can be available for multiple platforms -- e.g. as a set of Mac/Win/Linux executables.

**Comment by taskboy3000** [comment]
-1 "clever" code.

**Comment by jmacdotorg** [comment]
This will need to be delivered by July 1.

**Comment by jmacdotorg** [comment]
Changing the spec: the column should be an enum of all the platforms that the current web app currently recognizes, rather than a free-text field. This allows for the best compatibility with the way the rest of the code works now.

**Comment by jmacdotorg** [comment]
This is shipped!
