### ISSUE TITLE
Add a new account field for PayPal email address

### ISSUE THREAD

**Issue by jmacdotorg** [iftechfoundation/ifcomp#204]
**Deadline: July 1, 2020**

* Add a new field to account objects for a PayPal email address. It should mimic the format of account email address, with the exception that it is not required (i.e. NULL OK).

* Add support for this field to account the registration/update form, with similar validation checks to account email, with the exception that it is not required.

**Comment by erkyrath** [comment]
The question text should specify: "Please provide the email address of your Paypal account, *not* a paypal.me URL."

**Comment by jmacdotorg** [comment]
Closed with #214.
