### ISSUE TITLE
Support being an OAuth provider

### ISSUE THREAD

**Issue by curiousdannii** [iftechfoundation/ifcomp#215]
Introcomp shouldn't log in through a custom protocol but through standard OAuth

**Comment by jmacdotorg** [comment]
If we were doing this from scratch, then I agree that using a standard solution like OAuth would be a no-brainer. But we have what we have, and I'm not sure we'd gain much by tossing it out.

What's the argument for re-doing this?

**Comment by curiousdannii** [comment]
I'd expect that using a well supported library is less likely to have security holes than a custom handmade one. It also means that passwords etc won't ever be given to other sites (or sent over HTTP like for Introcomp.)

**Comment by curiousdannii** [comment]
Another option would be to use the Intfiction forum as a SSO provider. But it doesn't support OAuth currently.

**Comment by jmacdotorg** [comment]
Let's state that if in the future we determine that IFComp's auth system has security issues, then we should adopt a standard system like this. But until then, I don't feel the work would have clear enough benefit, so I'm closing this for now.

**Comment by curiousdannii** [comment]
But there are issues now. We need to close down the current system so that the other sites won't ask for passwords like they do now.

**Comment by jmacdotorg** [comment]
@curiousdannii, at your convenience, could you please clarify or enumerate the security issues facing the IFComp auth system, as it is right now?

(This is me believing you that there are some, and earnestly seeking your expertise in making their nature more clear! This way well turn into an important project for 2021.)

**Comment by curiousdannii** [comment]
The main issue is that by making it possible for other sites to log in via cleartext passwords we're encouraging them to do so, but also then putting all the security burden onto them and out of our control. And we're training users to put their IFComp passwords into other sites. It's unprofessional, and right now, an actual risk because not all partner sites are using HTTPS.
