### ISSUE TITLE
some links point to localhost:5000

### ISSUE THREAD

**Issue by andrewschultz** [iftechfoundation/ifcomp#217]
http://dev.ifcomp.org/entry/create "submit game information"

http://dev.ifcomp.org/entry "add a new entry" ./ "view all the feedback"

I imagine there's a way to audit the code for other places this may happen.

Tested in Firefox only.

**Comment by jmacdotorg** [comment]
This was due to incomplete configuration of the staging server. Please have another look at your convenience, @andrewschultz

**Comment by andrewschultz** [comment]
I tried plowing through all the links/looking at the source, and I wasn't able to find anything pointing to localhost. Closing.
