### ISSUE TITLE
Basic entry question

### ISSUE THREAD

**Issue by andrewschultz** [iftechfoundation/ifcomp#218]
http://dev.ifcomp.org/entry/create Basic Entry Information

Glulx and Z-code are listed together, except for "using Inform's release with a website feature" where they are listed separately.

This is obviously largely aesthetic, and there may be a good reason for doing so, anyway.

**Comment by jmacdotorg** [comment]
There *is* a reason, and the reason is that for this first pass I have kept the list of platforms exactly as they were in the list of automatically-recognized platforms.

I will acknowledge that this looks a tad weird and a candidate for future clarification, and close it for now.
