### ISSUE TITLE
It's no longer the 25th year, so the nice pig/stars graphic is out of date

### ISSUE THREAD

**Issue by andrewschultz** [iftechfoundation/ifcomp#227]
It'd be nice if it could be kept somewhere, but it is year 26 now. Time passes too fast.

**Comment by jmacdotorg** [comment]
Great catch! @Isquiesque has provided a tide-us-over graphic to slip in... attached.
![ifcomp-blankscreen](https://user-images.githubusercontent.com/621995/85959454-bc986f80-b96a-11ea-9702-299801cf3a5f.jpg)
