### ISSUE TITLE
dev.ifcomp.org can't upload cover files

### ISSUE THREAD

**Issue by andrewschultz** [iftechfoundation/ifcomp#230]
I've been unable to upload PNG files or JPG files. I've tried specifying Cover.PNG/JPG and sending images in different sizes. After hitting the "submit" button at the bottom, I see:

> Upload new cover art
> This doesn't appear to be a valid PNG or JPEG file.

Walkthrough and binary uploads work okay.

**Comment by jmacdotorg** [comment]
Marking as "major" in case it's somehow in prod as well. Will check asap.

**Comment by jmacdotorg** [comment]
Fixed; was due to some missing libraries, and this was a good catch because I bet our internal how-to-build-an-ifcomp-server recipe book doesn't account for them. I'll grumble in the appropriate directions.
