### ISSUE TITLE
International shipping options

### ISSUE THREAD

**Issue by mjmusante** [iftechfoundation/ifcomp#232]
Some people offer prizes that are physical items which need to be shipped. The software should have a way to capture the location a prize donor's will be shipping from, and whether the donor is willing to ship internationally.

**Comment by jmacdotorg** [comment]
* Add new fields to the DB
* Display appropriate stuff in the prize page whenever they're defined

No entry UI work need be done right now, since the prize coordinator updates the DB through manual SQL queries.

Also: This is a directive from comp chair, so high priority 👹
