### ISSUE TITLE
Review the ingestion procedure for Inform-authored games

### ISSUE THREAD

**Issue by jmacdotorg** [iftechfoundation/ifcomp#244]
Currently, for the sake of compatibility with the ifcomp.org-hosted interpreters as well as the transcription-recording system, the web application presents modified versions of some Inform-based games that it hosts. 

Details: https://github.com/iftechfoundation/ifcomp/wiki/IFComp-Game-file-management#how-entry-content-gets-processed

This was all programmed in 2014/2015, and changes have been made to many of the technologies involved since then. We should review these, and see if there's room to simplify things.

**Comment by curiousdannii** [comment]
Rather than trying to update interpreters, the mangling should probably be limited to inserting the transcript logging code.

**Comment by curiousdannii** [comment]
Btw, this is now causing major level bugs. If you're happy with what I said, then you can assign me.

**Comment by curiousdannii** [comment]
Seems I can't upload files here, so I uploaded the test zips to Slack.

So I realised my Perl knowledge is really so minimal that it probably would be easiest for you to do it. But, I can tell you what needs to be done!

# Old Parchment

String to match: `Parchment requires Javascript.`

Add before `</head>`:

```
<script src="/static/interpreter/transcript_recorder/if-recorder.js"></script>
<script>
ifRecorder.saveUrl = "/play/$entry_id/transcribe";
ifRecorder.story.name = "$title";
ifRecorder.story.version = "1";
</script>
```

# Old Parchment

String to match: `Parchment requires Javascript.`

Add before `</head>`:

```
<script src="/static/interpreter/transcript_recorder/if-recorder.js"></script>
<script>
ifRecorder.saveUrl = "/play/$entry_id/transcribe";
ifRecorder.story.name = "$title";
ifRecorder.story.version = "1";
</script>
```


PS: why is the stuff about making websites in **Result**/Entry.pm??
