### ISSUE TITLE
Customise Catalyst error page

### ISSUE THREAD

**Issue by curiousdannii** [iftechfoundation/ifcomp#263]
![Screenshot of the default Catalyst error page](https://user-images.githubusercontent.com/59074/94084649-575cf900-fe49-11ea-9db7-0764fac94ba8.png)

This default Catalyst error page is so different from the rest of the site that I thought entrants were uploading it themselves when they hadn't finished their entry yet.

Would it be possible to customise the error page so that it resembles the rest of the site?

**Comment by adherzog** [comment]
https://metacpan.org/pod/distribution/Catalyst-Manual/lib/Catalyst/Manual/Cookbook.pod#Delivering-a-Custom-Error-Page

**Comment by curiousdannii** [comment]
Oops, didn't notice this is a duplicate of #167
