### ISSUE TITLE
Automatically add entrants to forum's private authors group

### ISSUE THREAD

**Issue by curiousdannii** [iftechfoundation/ifcomp#265]
It wouldn't be too hard to make the comp site automatically add entrants to the private forum group. What would be needed:

1. A private setting for the forum's API access key (needs to be kept safe along with the other secrets the site uses)
2. A new field for each year's competition for the ID number of that year's private authors group
3. When the competition is launched, either:
   1. 1. Query the forum's API to see if a user exists with the entrant's email address
       2. If so, make the API call to add them to this year's group
   2. Make an API call to add them by usernames

It's simpler to just send usernames (you could do it in just one API request!), but safer to do it by email address, because you don't validate the usernames, and people might copy in their "display name" instead of their username.

Actually the comp could even create the group, it would probably only be one API request too. For that matter it could also create the private sub-category! I think it would just be one more API request.

It would also be possible to send an email invite to anyone who doesn't already have a forum account, and if they sign up they would be automatically added to the group.

**Comment by jmacdotorg** [comment]
Comp leadership currently does this manually. I'll make sure they know there's an option to do this automatically, if they feel it's important to implement.
