### ISSUE TITLE
Authors should be able to set the Download field without needing to upload a zip

### ISSUE THREAD

**Issue by tavinstitute** [iftechfoundation/ifcomp#266]
Lacking the ability to set an external URL for this will require the following, in order to produce any clear user path to offline usage:
- Quadrupling the POST limits for the IFComp Server from 250MB to >1GB.
- Serving 1GB of Content to every Player who wishes to Play any portion of the Game offline.

The former will be a serious security risk, and the latter can potentially destabilize steady access to other Games, which would be an unfair use of resources on Our part.

**Comment by jmacdotorg** [comment]
The more general issue alluded to in the issue text here is an important one for administrative discussion as the comp keeps serving more, and larger, entries year-over-year.

I'm going to close this as a tech suggestion but will pass its underlying issue along as an important topic to resolve before next year's comp.
