### ISSUE TITLE
Removing coauthored work gives "come back later" page

### ISSUE THREAD

**Issue by andrewschultz** [iftechfoundation/ifcomp#312]
On http://dev.ifcomp.org/entry,

1. create a new entry with account A
2. log in with account B and use the coauthor code so you are the coauthor
3. click "withdraw" and check the box

Note you get the "come back later" page instead of an updated page. Also, the entry is not removed.

It appears the main author would just need to remove coauthors and then delete the entry for things to work, so there is a workaround.

Deleting an entry before adding coauthors, or after deleting them, works okay.

**Comment by adherzog** [comment]
This has been resolved - entries with co-authors can now be withdrawn without any errors.
