### ISSUE TITLE
Error in "Under the Bridge" submission to IF Archive

### ISSUE THREAD

**Issue by dfabulich** [iftechfoundation/ifcomp#373]
https://unbox.ifarchive.org/?url=/if-archive/games/competition2022/Games/Under%20the%20Bridge.zip

Under the Bridge is a Twine game https://ifcomp.org/ballot#entry-2699 and it has a “Play online” button on the ballot, but the IF Archive zip is nothing but its Cover Art image.

https://ifarchive.org/if-archive/games/competition2022/Games/Under%20the%20Bridge.zip contains a suspiciously empty folder called IF Comp - Entry. I think this an error in the big zip somehow.

**Comment by mjmusante** [comment]
root cause: the current ifarchive zip-up script has not yet been fixed to handle the new method of uploading to the archive (a zip of zipfiles instead of a zip of the unzipped directories). The zip-of-zips that was uploaded to the archive was created by hand and I goofed along the way

**Comment by erkyrath** [comment]
A new IFComp2022.zip and Under_the_Bridge.zip have been uploaded to ifarchive.org. I moved them into place at games/competition2022.
