### ISSUE TITLE
Feature request: Implement voting in the games listing

### ISSUE THREAD

**Issue by angstsmurf** [iftechfoundation/ifcomp#382]
It would be nice to be able to vote directly in [the games listing](https://ifcomp.org/ballot), without having to open [a different page](https://ifcomp.org/ballot/vote) and find the game you want to vote for. This was briefly discussed on the forum:
[IF Comp site: Why is rating on a separate page?](https://intfiction.org/t/if-comp-site-why-is-rating-on-a-separate-page/64929)

I thought there should be an issue here as well, so that it won't be forgotten.

EDIT: This is apparently a duplicate of #200.

**Comment by mjmusante** [comment]
So, as it turns out, this WAS implemented! Issue #223 

But there's been a bug in there all along, preventing the voting/feedback div from showing up. Sigh
