### ISSUE TITLE
Use links rather than buttons for Download, Play Online etc

### ISSUE THREAD

**Issue by curiousdannii** [iftechfoundation/ifcomp#40]
The website uses forms and buttons on [the entries page](http://ifcomp.org/ballot/), which means that you can't directly access the URLs. Looking at the HTML I can't see any reason why they couldn't be replaced with links instead.

[The code in question](https://github.com/jmacdotorg/ifcomp/blob/master/IFComp/root/src/_current_entry_row.tt#L37). I'd submit a pull request but I don't know the templating system and wouldn't be able to test it. But I'd guess something like this:

```
        <a href="[% c.uri_for_action( '/play/download', [ entry.id] ) %]" class="btn btn-default btn-lg">
            <span class="glyphicon glyphicon-cloud-download"></span> Download
        </a>
```

**Comment by jmacdotorg** [comment]
Fixed, with #88.
