### ISSUE TITLE
Add microdata to the `games.html` cover sheet

### ISSUE THREAD

**Issue by dfabulich** [iftechfoundation/ifcomp#423]
We have microdata on the `/ballot` page, but it would be useful to also have it in the `games.html` cover sheet.

(I intend to file a PR for this, if I can get the dev environment to work for me.)

**Comment by UncleScientist** [comment]
If you have any difficulties with getting the dev environment working, please ping me on the iftf slack. We should make sure that the contributing doc page has all the information necessary for someone to get started quickly.
