### ISSUE TITLE
Can judges have the option to remove voted-on entries from https://ifcomp.org/ballot/?

### ISSUE THREAD

**Issue by andrewschultz** [iftechfoundation/ifcomp#431]
What the title says. As someone who wants to vote on half the entries, there's some wrangling when I want to look for something I haven't played yet.

I don't know the level of difficulty involved in sorting games by play time, but if sorting by "voted/not voted" is not too difficult, it might help judges who want to throw in a bunch of votes organize things.

**Comment by erkyrath** [comment]
There has to be a way to change your vote *somewhere*.

**Comment by Keltena** [comment]
> There has to be a way to change your vote _somewhere_.

You can do that on /ballot/vote. /ballot is the page with the full blurbs/cover art/links.

**Comment by mjmusante** [comment]
This sounds like a good enhancement - adding a checkbox to say "hide entries that I've already voted on"
