### ISSUE TITLE
carriage returns hard/impossible to create for entry updates?

### ISSUE THREAD

**Issue by andrewschultz** [iftechfoundation/ifcomp#435]
I've tried the following sort of text in an update:

--big important bug fixed (e.g. runtime error/unwinnable state)
--medium sized bug fixed (e.g. HINT gives blank response for useless stuff)
--small bug fixed (e.g. various typos)
--trivial assembly bug fixed (e.g. walkthrough update)

I've tried double line breaks, too.

The problem is, whatever I try creates 1 line instead of 4, which is hard to read.

I've considered adding HTML tags e.g. <br /> but I don't want to force things & make an update especially unreadable.

I like to organize updates by most severe bug to least severe so the judges can see what happened at a glance/if it's worth downloading an update. And I think it's general good form to do this, especially since entrants don't want to update for every trivial typo.

Is there a quick way to allow a markup-style? Or if it's there, and I'm missing it, inform entrants how you can create a line break?

**Comment by mjmusante** [comment]
i edited-in-prod a fix for this, will make it official this evening. Not full markdown, but at least newline-preserving

**Comment by andrewschultz** [comment]
Wow, this looks really neat. Great to have the old updates back-fitted, too, Thanks for the quick fix!
