### ISSUE TITLE
Interface bug on uploading files

### ISSUE THREAD

**Issue by andrewschultz** [iftechfoundation/ifcomp#51]
1. http://dev.ifcomp.org/entry/1325/update
2. click "upload a new game file" and upload any file
3. click "upload a new game file" and hit escape

The chosen file is deleted. This might be a minor nuisance if someone hit "upload" twice by mistake. But they can always just re-type the file name in, and with file/tab completion etc. they can recover. So is it worth checking that there already is a filename?

**Comment by jmacdotorg** [comment]
I can't reproduce this. Does this happen regardless of browser used? (I sorta suspect that this is browser-specific behavior...)

**Comment by jmacdotorg** [comment]
Resolved in email.
