### ISSUE TITLE
Use Quixe for web-play of Glulx games

### ISSUE THREAD

**Issue by erkyrath** [iftechfoundation/ifcomp#66]
Currently the site throws both Z-code and Glulx games to Parchment. Parchment's Quixe plugin is buggy -- most obviously, it fails to show the status line. Quixe as a separate install works better.

**Comment by danshiovitz** [comment]
Does the if-recorder stuff for keeping transcripts work with standalone quixe?

**Comment by erkyrath** [comment]
I added a version of that to quixe, yes. I don't promise that it's web-API-identical to the current system. Will have to be tested.

**Comment by curiousdannii** [comment]
I agree it's safer to use Quixe directly, but if you updated Parchment to the code in the gh-pages branch then the status line bug would be fixed too.

**Comment by jmacdotorg** [comment]
@danshiovitz - Did you end up making progress on this? I'd like to see it in-place before October 2017.

(Would be willing to take it off your hands if you'd rather... I have motivation to work on this now and only now discovered that someone else had picked it up.)

See also a wiki page I just made about how online play & transcription currently works: https://github.com/iftechfoundation/ifcomp/wiki/Online-play-and-transcription-recording

**Comment by danshiovitz** [comment]
I don't think I made major progress but I don't remember why - probably better for me just to hand it off and you start fresh.

**Comment by jmacdotorg** [comment]
Fixed, via #117.
