### ISSUE TITLE
Html playfile selection is incorrect

### ISSUE THREAD

**Issue by danshiovitz** [iftechfoundation/ifcomp#70]
jmac [12:42 PM]  
Eurgh… @danshiovitz, looks like the fix to the broken-web-links issue raised a problem for games with multiple .html files at the top level, even if one is named index.html
In at least one case (Detectiveland) the code now opens the wrong file. In this case the author fixed it himself by moving the not-index file elsewhere, but.

danshiovitz [1:30 PM]  
whoops, I guess the rule should be to prefer index.htm(l), then alphabetically first other .html
or it could be that if there's just a single html file, use that, otherwise use index.html whether or not it exists
essentially forcing them to disambiguate themselves

jmac [1:48 PM]  
Yeah, I think that’s a good way to appraoch it.

danshiovitz [1:56 PM]  
the latter?

jmac [1:57 PM]  
Right.

[1:58]  
And to be clear, it should consider only HTML files at the top level when it’s making this choice

[1:58]  
So if it has /game.html and /extra/hints.html it won’t get confused.

[1:59]  
But if it has those two, and also /poster.html, then all bets are off. But /index.html would be fine.

**Comment by jmacdotorg** [comment]
#71 attends to this, but I'm making an executive decision to delay further action on it until after November 15.
