### ISSUE TITLE
Cover images on ballot page should be optimized

### ISSUE THREAD

**Issue by adherzog** [iftechfoundation/ifcomp#76]
The full size cover images being used on the ballot page are huge, compared to what's needed, causing for a very slow first time load. Also, since the image dimensions are not part of the markup, the page keeps jumping as new images are loaded.

We should shrink or otherwise optimize the images, and add some css/markup to prevent the page from jumping as the images load.

**Comment by jmacdotorg** [comment]
Yep, agreed.

I wrote a script to resize all the images last year. I searched in vain for it last week. :/

My proposal to amend this has two parts:

1. 🎶Someone🎶 can recreate a simple one-off script that chows through entries/*/cover, resizing all the images to something saner. That'll take care of this year.

1. We add a more strict image-file-size maximum to the entry form so this won't be an issue in future comp years.

**Comment by jmacdotorg** [comment]
Let's break it up this way:

1. I rewrite and run that script ASAP

1. Please do provide suggestions for stopping the jumpy redraws?

1. As a future (post-comp) task, implement (2), above.

**Comment by adherzog** [comment]
Running a script (or imagemagick command, or whatever) to resize the cover images is the best immediate solution.That alone will probably fix the jumping enough that everything else could be addressed post-comp.

I'm not sure I understand why the cover images are served through Catalyst, rather than just serving static files directly through Apache/Nginx. I'd usually suggest resizing images (and maybe converting to a single format - png or jpeg) when they are uploaded, and saving them into eg images/<COMP_YEAR>/<ENTRY_ID> or whatever. That'd make it easy to build the img tag, and it'd be much quicker to serve to the user.

I also see a separate Cover model that already exists, but I'm not sure what that's for. Not the current year's entries, I guess. Could it be? (Incidentally, the model is Model::Cover, but there's config in IFComp.pm for Model::Covers.)

I've used Template::Plugin::Image before to build image tags with dimensions. That'd solve the jumping page problem completely. It's some extra processing to build the page, for sure, but if we're caching that ballot page then it might not matter. (And we should be, right? It's probably the most popular page during the comp, and contains lots of db lookups, etc.)

**Comment by adherzog** [comment]
Oh, I just realized that the full year's .zip download has full size cover images. I think that's a good idea. Can you keep that if you resize all the cover images?

**Comment by jmacdotorg** [comment]
I just resized all the images on /ballot to a maximum height of 350px (matching the CSS max-height directive on that page). Good enough to ride out the comp, by your eye?

(Yes, this does not effect the full-comp .zip downloads, nor what'll go into the archive.)

**Comment by adherzog** [comment]
It's a significant improvement.

**Comment by jmacdotorg** [comment]
One reason I haven't used e.g. Template::Plugin::Image is that the image dimensions are flexible; their width is measured in columns, as dictated by Bootstrap. I haven't looked into how to do that properly. I think we should do that before I shut this ticket. Suggestions welcome.

Yes, the page is cached server-side (as are all the pages on the website) unless you are logged in. (Which you won't be, on your first visit.)

**Comment by jmacdotorg** [comment]
Marking this as a bug and not an enhancement because when this problem is in full force with lots of entries, the ballot page really does look & act awful. Needs a permanent and elegant fix.

**Comment by jmacdotorg** [comment]
Fixed with #138, which creates scaled-down web-display versions of uploaded cover art as needed.
