### ISSUE TITLE
Night House has Web format instead of Quest

### ISSUE THREAD

**Issue by dougo** [iftechfoundation/ifcomp#77]
The entry "Night House" in the 2016 comp is a Quest game, and one of its files is `nighthouse.quest`, but it's shown as "Format: Web". There is an `index.html` file that has a link to the game's page on http://textadventures.co.uk/, but the entry's blurb suggests "Download for best experience". I think ideally it should say "Format: Quest" but also have a "> Play online" button that links to textadventures.co.uk (in the same way that Glulx entries have a "> Play online" button that links to a local Quixe page).

Note that the entry "Eight characters, a number, and a happy ending" is also a Quest game, but that comp entry consists solely of an HTML page that has a link to textadventures.co.uk (where, by the way, you can download the `.quest` file). I suppose the author might prefer to have people download from that site rather than from the ifcomp site, but I'm guessing they didn't have a preference and it just seemed easier this way?

**Comment by jmacdotorg** [comment]
I have ideas on how to resolve this, but I want to finish merging #71 first, since it refactors how the software determines what platform a game uses.

**Comment by jmacdotorg** [comment]
This did indeed get resolved on or around the merging of #71.
