### ISSUE TITLE
Markup/markdown for blurb is unclear/inconsistent

### ISSUE THREAD

**Issue by andrewschultz** [iftechfoundation/ifcomp#83]
1 log in to the dev server
2 create a new game
3 create a blurb

Note that if we have text like
`Line 1
Line 2`

There is no carriage return between the two unless we throw in another carriage return, which suggests that the input understands some sort of markup. But trying * or - or _ or anything like that turns up nothing. I think it would be nice to allow the participant to do stuff like bold or italics and to provide some sort of brief documentation. If we can't, should we get rid of the need for 2 carriage returns to make a line break in the final blurb?

This is a minor inconvenience since people will have plenty of time to tweak their blurbs through trial and error, but a bit of documentation would be nice. And I could see a participant adjusting their blurb and forgetting the carriage return mid-comp, which isn't disastrous but it's still a bit of a nuisance.

**Comment by jmacdotorg** [comment]
I don't want unconstrained mark(up/down). I could see allowing italics or bold but, I'll be honest, I kind of like going roman-only, here.

But we do allow paragraph breaks, and I agree I should better label what's allowed, so I'll add a note.

**Comment by jmacdotorg** [comment]
@andrewschultz Could you please look at #95? See especially the change highlighted under the "files changed" tab. Is that adequate documentation to display over the blurb form field?

(I'd add you as a code-reviewer on that ticket but GitHub won't let me... I think you have to be among the official "collaborators" on this repo, perhaps. I've separately sent you an invitation to this end.)

**Comment by andrewschultz** [comment]
@jmacdotorg thanks for mentioning that here. I didn't get the email, or it got lost in the shuffle of all the other stuff I got from github. So, sorry for the delay. It looks like I'll need to send "iftechfoundation" emails from GitHub to my IF folder and not github.
