### ISSUE TITLE
abuse case for participant creating 4 entries

### ISSUE THREAD

**Issue by andrewschultz** [iftechfoundation/ifcomp#85]
I think I found a case like this earlier, but I wasn't sneaky enough to catch them all.

* create an entry
* create another entry
* open the "register or manage your entries" in 2 tabs
* in each tab click "add a new game"
* make a title then in each tab click "submit"

You have 4 entries now...so I think IFComp.org needs to check for # of entries when the "submit" button is pushed too.

**Comment by jmacdotorg** [comment]
Yes, the controller that handles the entry form should check whether the author has room for more entries, and display an appropriate form-error (otherwise persevering form contents) if they don't.
