### ISSUE TITLE
"page not found" error

### ISSUE THREAD

**Issue by andrewschultz** [iftechfoundation/ifcomp#86]
http://www.ifcomp.org/entry/160/update redirects us to the home page

http://www.ifcomp.org/entry/160/updat gives "page not found"

This is cosmetic, but if there's a quick fix, it'd still be nice if we could redirect bad sublinks to the home page.

http://www.ifcomp.org/entry/x

http://www.ifcomp.org/ent

Are similar cases that might be worth a look.

**Comment by jmacdotorg** [comment]
I'd rather that requests for nonexistent pages (versus extant pages that you don't have permission to visit) return a 404 error.

**Comment by adherzog** [comment]
Maybe forbidden pages should return a 403 then? In either case, maybe we could open a separate issue to add a better 404 page (and 403, if appropriate) that looks like an actual page with links to the homepage?

**Comment by jmacdotorg** [comment]
Both of these sound like splendid pull requests. :)
