### ISSUE TITLE
Fix tests to work from fresh checkout

### ISSUE THREAD

**Issue by adherzog** [iftechfoundation/ifcomp#97]
Need to create some missing directories - t/db and t/entries (?).

Update test files to use test db instead of mysql db.

**Comment by adherzog** [comment]
@jmacdotorg I don't have the necessary privileges to setup Travis CI on my own. Could you activate the repo, please? It should be a matter of going to https://travis-ci.org/iftechfoundation/ifcomp, logging in to your GitHub account (I think it does the OAuth thing), and then clicking the big, green 'Activate Repo' button. Or, you can give me admin access to the ifcomp repo and that should allow me to do it.

**Comment by jmacdotorg** [comment]
@adherzog: I did the stuff. Please proceed at will...

**Comment by adherzog** [comment]
Fixed.
