### ISSUE TITLE
Support for prize pool fundraiser

### ISSUE THREAD

**Issue by erkyrath** [iftechfoundation/ifcomp#99]
Starting July 1, the web site will be hosting a fundraiser for IFComp prize money. This entails new stuff on the front page: a classic green fundraiser bar that goes from $0 to $6000, and some other associated numbers.

I will also need an administrative page where I can go in (at least daily, probably more often some days) to update the current fundraiser total. And maybe the other associated numbers.

I'm writing these requirements up on a functional basis -- you folks can decide how it looks on the site. Except that the green bar is mandatory. Can't have a fundraiser without a green bar. :)

## Variables in the database:

- $GOAL (dollars): Fundraiser goal amount. Initially 6000, but we might decide to adjust it.
- $AMOUNT (dollars): How much money people have donated. Initially zero. This may wind up exceeding $GOAL.
- $MINPRIZE (dollars): Lowest prize level. Initially 10. Probably won't change but you never know.
- $ENTRIES (int): An estimate of the number of IFComp entries. Initially 60.

The admin page should let me edit any of these. But of course $AMOUNT will change more frequently than the others.

When I say "me", I mean me as IFTF treasurer, Jmac as Comp Cheez, and anybody else with relevant authority.

## Derived values:

- $POOL (dollars) = 0.8 * MIN($GOAL, $AMOUNT). Current prize pool size.
- $WINNERS (int) = ROUND(0.6667 * $ENTRIES). Approximate number of entries which will win cash from the pool.
- $TEMP (dollars) = 3 * ($POOL - $MINPRIZE * $WINNERS) / $WINNERS.
- $MAXPRIZE (dollars) = $TEMP * (((0.5 / $WINNERS) - 1) ^ 2) + $MINPRIZE. Estimated highest prize level.

I apologize for the baroque computation of $MAXPRIZE. It works out.

Examples: given $ENTRIES of 60, $WINNERS will be 40. If $AMOUNT is 1000, then $POOL will be 800 and $MAXPRIZE will be 39.25. if we surpass our goal and $AMOUNT is greater than 6000, then $POOL will max out at $4800, and $MAXPRIZE will be 331.80.

Note that when $AMOUNT is small, $MAXPRIZE is negative. This is a nonphysical solution which occurs when we can't guarantee $MINPRIZE to everybody. Don't worry about it, we'll just hide that until $AMOUNT becomes large enough.

## Information to display:

$AMOUNT in dollars. This is the headline number -- total donations. It may exceed $GOAL.

Green bar displaying $AMOUNT on a range of 0 to $GOAL. If $AMOUNT exceeeds $GOAL, the green bar maxes out but the site should display an additional "Goal reached! Thank you all!" message.

In smaller print: "Current cash prize pool is $POOL." Then, displayed *only if* $MAXPRIZE > $MINPRIZE: "First-place cash prize will be approximately $MAXPRIZE. (Assuming $ENTRIES IFComp entries.)"

Naturally there must be a prominent Paypal button. I will attach the HTML to embed that.

And we want a link to the fundraiser FAQ, which I guess will be a post on blog.ifcomp.org.

**Comment by erkyrath** [comment]
Paypal button form:

[button.txt](https://github.com/iftechfoundation/ifcomp/files/1055972/button.txt)

**Comment by adherzog** [comment]
Why was this closed? There's no explanation or anything... has the fundraiser been cancelled/postponed or something?

**Comment by jmacdotorg** [comment]
No, but I decreed that this wasn't where this goes. (I've moved this to a private Trello.)
